# Selecting Base OS
FROM ubuntu                            

# Dockerfile Maintainer
MAINTAINER "ankit@gmail.com"            

# Installing nginx 
RUN  apt update && apt install nginx -y    

#expose port 80
EXPOSE 80

# Start Nginx
CMD ["/usr/sbin/nginx"]                  

