
FROM ubuntu                             # selecting Base OS

MAINTAINER "ankit@gmail.com"             # Dockerfile Maintainer

RUN  apt update && apt install nginx -y    # Installing nginx 

CMD ["/usr/sbin/nginx"]                   # Start Nginx

